# Generated by Django 4.2.20 on 2025-03-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0003_rename_author_question_author_id_answer_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="author_id",
            new_name="author",
        ),
    ]
