# Generated by Django 4.2.20 on 2025-03-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0004_rename_author_id_question_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
